# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.17"
  amd64: "ghcr.io/home-assistant/amd64-base:3.17"
  i386: "ghcr.io/home-assistant/i386-base:3.17"
labels:
  org.opencontainers.image.title: "ebusd thermostat"
  org.opencontainers.image.description: "Control your ebus heater connected via ebusd"
  org.opencontainers.image.source: "https://github.com/wannes-ds/hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
